// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademyAgain.Migrations
{
    [DbContext(typeof(AcademyAgainContext))]
    [Migration("20260922014827_SupportSchema")]
    partial class SupportSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademyAgain.Models.AdmissionRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("direction_id")
                        .HasColumnType("INT");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<byte>("status")
                        .HasColumnType("TINYINT");

                    b.HasKey("id");

                    b.ToTable("AdmissionRequests");
                });

            modelBuilder.Entity("AcademyAgain.Models.Attendance", b =>
                {
                    b.Property<int>("student")
                        .HasColumnType("int");

                    b.Property<long>("lesson")
                        .HasColumnType("BIGINT");

                    b.Property<bool>("present")
                        .HasColumnType("BIT");

                    b.HasKey("student", "lesson");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("AcademyAgain.Models.CandidateRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("candidate_user_id")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("DATETIME");

                    b.Property<byte>("status")
                        .HasColumnType("TINYINT");

                    b.Property<int>("teacher_id")
                        .HasColumnType("INT");

                    b.HasKey("id");

                    b.ToTable("CandidateRequests");
                });

            modelBuilder.Entity("AcademyAgain.Models.CompleteDiscipline", b =>
                {
                    b.Property<int>("group")
                        .HasColumnType("int");

                    b.Property<short>("discipline")
                        .HasColumnType("SMALLINT");

                    b.HasKey("group", "discipline");

                    b.ToTable("CompleteDisciplines");
                });

            modelBuilder.Entity("AcademyAgain.Models.DaysOFF", b =>
                {
                    b.Property<DateTime>("date")
                        .HasColumnType("DATE");

                    b.Property<byte>("holiday")
                        .HasColumnType("TINYINT");

                    b.HasKey("date");

                    b.ToTable("DaysOFF");
                });

            modelBuilder.Entity("AcademyAgain.Models.DependentDiscipline", b =>
                {
                    b.Property<short>("discipline")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("dependent_discipline")
                        .HasColumnType("SMALLINT");

                    b.HasKey("discipline", "dependent_discipline");

                    b.ToTable("DependentDisciplines");
                });

            modelBuilder.Entity("AcademyAgain.Models.Direction", b =>
                {
                    b.Property<byte>("direction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("direction_id"));

                    b.Property<string>("direction_name")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("direction_id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("AcademyAgain.Models.Discipline", b =>
                {
                    b.Property<short>("discipline_id")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("discipline_name")
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<byte>("number_of_lessons")
                        .HasColumnType("TINYINT");

                    b.HasKey("discipline_id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("AcademyAgain.Models.DisciplinesDirectionsRelation", b =>
                {
                    b.Property<byte>("direction")
                        .HasColumnType("TINYINT");

                    b.Property<short>("discipline")
                        .HasColumnType("SMALLINT");

                    b.HasKey("direction", "discipline");

                    b.ToTable("DisciplinesDirectionsRelation");
                });

            modelBuilder.Entity("AcademyAgain.Models.EmailVerificationCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte>("attempts")
                        .HasColumnType("TINYINT");

                    b.Property<string>("code_hash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<bool>("consumed")
                        .HasColumnType("BIT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("DATETIME");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("DATETIME");

                    b.Property<string>("pending_first_name")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("pending_last_name")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("pending_middle_name")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("pending_password_hash")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("pending_phone")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte?>("pending_role_id")
                        .HasColumnType("TINYINT");

                    b.Property<string>("pending_username")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<byte>("purpose")
                        .HasColumnType("TINYINT");

                    b.Property<int?>("user_id")
                        .HasColumnType("INT");

                    b.HasKey("id");

                    b.HasIndex("email", "purpose", "consumed");

                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("AcademyAgain.Models.Exam", b =>
                {
                    b.Property<int>("student")
                        .HasColumnType("int");

                    b.Property<short>("discipline")
                        .HasColumnType("SMALLINT");

                    b.Property<DateTime?>("date")
                        .HasColumnType("DATE");

                    b.Property<byte?>("grade")
                        .HasColumnType("TINYINT");

                    b.HasKey("student", "discipline");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("AcademyAgain.Models.Grade", b =>
                {
                    b.Property<int>("student")
                        .HasColumnType("int");

                    b.Property<long>("lesson")
                        .HasColumnType("BIGINT");

                    b.Property<byte?>("grade_1")
                        .HasColumnType("TINYINT");

                    b.Property<byte?>("grade_2")
                        .HasColumnType("TINYINT");

                    b.HasKey("student", "lesson");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("AcademyAgain.Models.Group", b =>
                {
                    b.Property<int>("group_id")
                        .HasColumnType("int");

                    b.Property<byte?>("direction")
                        .HasColumnType("TINYINT");

                    b.Property<string>("group_name")
                        .HasColumnType("NCHAR(10)");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("DATE");

                    b.Property<TimeSpan?>("start_time")
                        .HasColumnType("TIME");

                    b.Property<byte?>("weekdays")
                        .HasColumnType("TINYINT");

                    b.HasKey("group_id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AcademyAgain.Models.Holiday", b =>
                {
                    b.Property<byte>("holiday_id")
                        .HasColumnType("TINYINT");

                    b.Property<byte?>("day")
                        .HasColumnType("TINYINT");

                    b.Property<byte>("duration")
                        .HasColumnType("TINYINT");

                    b.Property<string>("holiday_name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<byte?>("month")
                        .HasColumnType("TINYINT");

                    b.HasKey("holiday_id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("AcademyAgain.Models.News", b =>
                {
                    b.Property<int>("news_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("news_id"));

                    b.Property<int?>("author_id")
                        .HasColumnType("INT");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("is_published")
                        .HasColumnType("BIT");

                    b.Property<DateTime?>("published_at")
                        .HasColumnType("DATETIME");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("news_id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("AcademyAgain.Models.Project", b =>
                {
                    b.Property<int>("project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("project_id"));

                    b.Property<byte[]>("cover")
                        .HasColumnType("IMAGE");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("DATETIME");

                    b.Property<string>("description")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<bool>("pinned")
                        .HasColumnType("BIT");

                    b.Property<byte>("status")
                        .HasColumnType("TINYINT");

                    b.Property<string>("tags")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("url")
                        .HasColumnType("NVARCHAR(300)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("project_id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AcademyAgain.Models.RequiredDiscipline", b =>
                {
                    b.Property<short>("discipline")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("required_discipline")
                        .HasColumnType("SMALLINT");

                    b.HasKey("discipline", "required_discipline");

                    b.ToTable("RequiredDisciplines");
                });

            modelBuilder.Entity("AcademyAgain.Models.Role", b =>
                {
                    b.Property<byte>("role_id")
                        .HasColumnType("TINYINT");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AcademyAgain.Models.Salary", b =>
                {
                    b.Property<long>("payment_id")
                        .HasColumnType("BIGINT");

                    b.Property<decimal>("accrued")
                        .HasColumnType("SMALLMONEY");

                    b.Property<bool>("received")
                        .HasColumnType("BIT");

                    b.Property<short>("teacher")
                        .HasColumnType("SMALLINT");

                    b.HasKey("payment_id");

                    b.ToTable("Salary");
                });

            modelBuilder.Entity("AcademyAgain.Models.Schedule", b =>
                {
                    b.Property<long>("lesson_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("lesson_id"));

                    b.Property<DateTime?>("date")
                        .HasColumnType("DATE");

                    b.Property<short>("discipline")
                        .HasColumnType("SMALLINT");

                    b.Property<byte>("duration_min")
                        .HasColumnType("TINYINT");

                    b.Property<int>("group")
                        .HasColumnType("int");

                    b.Property<short?>("semester_id")
                        .HasColumnType("SMALLINT");

                    b.Property<bool>("spent")
                        .HasColumnType("BIT");

                    b.Property<short>("teacher")
                        .HasColumnType("SMALLINT");

                    b.Property<TimeSpan?>("time")
                        .HasColumnType("TIME");

                    b.HasKey("lesson_id");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("AcademyAgain.Models.Semester", b =>
                {
                    b.Property<int>("semester_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("semester_id"));

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("DATE");

                    b.Property<bool>("is_current")
                        .HasColumnType("BIT");

                    b.Property<bool>("is_even_week_start")
                        .HasColumnType("BIT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("DATE");

                    b.HasKey("semester_id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("AcademyAgain.Models.SessionRule", b =>
                {
                    b.Property<int>("session_rule_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("session_rule_id"));

                    b.Property<bool>("is_active")
                        .HasColumnType("BIT");

                    b.Property<byte>("min_attendance_pct")
                        .HasColumnType("TINYINT");

                    b.Property<decimal>("min_average_grade")
                        .HasColumnType("DECIMAL(3,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte>("required_makeups")
                        .HasColumnType("TINYINT");

                    b.HasKey("session_rule_id");

                    b.ToTable("SessionRules");
                });

            modelBuilder.Entity("AcademyAgain.Models.Student", b =>
                {
                    b.Property<int>("stud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stud_id"));

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("DATE");

                    b.Property<string>("email")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int?>("group")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("middle_name")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("phone")
                        .HasColumnType("NCHAR(16)");

                    b.Property<byte[]>("photo")
                        .HasColumnType("IMAGE");

                    b.HasKey("stud_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AcademyAgain.Models.SupportBan", b =>
                {
                    b.Property<int>("ban_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ban_id"));

                    b.Property<int>("chat_id")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("moderator_user_id")
                        .HasColumnType("INT");

                    b.Property<string>("reason")
                        .HasColumnType("NVARCHAR(300)");

                    b.Property<int>("user_id")
                        .HasColumnType("INT");

                    b.HasKey("ban_id");

                    b.ToTable("SupportBans");
                });

            modelBuilder.Entity("AcademyAgain.Models.SupportChat", b =>
                {
                    b.Property<int>("chat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chat_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("DATETIME");

                    b.Property<byte>("status")
                        .HasColumnType("TINYINT");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("DATETIME");

                    b.Property<int>("user_id")
                        .HasColumnType("INT");

                    b.HasKey("chat_id");

                    b.HasIndex("user_id");

                    b.ToTable("SupportChats");
                });

            modelBuilder.Entity("AcademyAgain.Models.SupportMessage", b =>
                {
                    b.Property<int>("msg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("msg_id"));

                    b.Property<int>("author_user_id")
                        .HasColumnType("INT");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("chat_id")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("DATETIME");

                    b.HasKey("msg_id");

                    b.HasIndex("chat_id");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("AcademyAgain.Models.Teacher", b =>
                {
                    b.Property<short>("teacher_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("teacher_id"));

                    b.Property<DateTime?>("birth_date")
                        .HasColumnType("DATE");

                    b.Property<string>("email")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("first_name")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("last_name")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("middle_name")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("phone")
                        .HasColumnType("NCHAR(16)");

                    b.Property<byte[]>("photo")
                        .HasColumnType("IMAGE");

                    b.Property<decimal?>("rate")
                        .HasColumnType("SMALLMONEY");

                    b.Property<DateTime?>("work_since")
                        .HasColumnType("DATE");

                    b.HasKey("teacher_id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("AcademyAgain.Models.TeachersDisciplinesRelation", b =>
                {
                    b.Property<short>("teacher")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("discipline")
                        .HasColumnType("SMALLINT");

                    b.HasKey("teacher", "discipline");

                    b.ToTable("TeachersDisciplinesRelation");
                });

            modelBuilder.Entity("AcademyAgain.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<byte[]>("banner")
                        .HasColumnType("IMAGE");

                    b.Property<string>("bio")
                        .HasColumnType("NVARCHAR(300)");

                    b.Property<string>("contact")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("email")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int?>("linked_id")
                        .HasColumnType("INT");

                    b.Property<string>("middle_name")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<byte[]>("photo")
                        .HasColumnType("IMAGE");

                    b.Property<byte>("role_id")
                        .HasColumnType("TINYINT");

                    b.Property<byte>("status")
                        .HasColumnType("TINYINT");

                    b.Property<string>("tagline")
                        .HasColumnType("NVARCHAR(80)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("user_id");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AcademyAgain.Models.Vacancy", b =>
                {
                    b.Property<int>("vacancy_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vacancy_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("DATETIME");

                    b.Property<string>("description")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int?>("discipline_id")
                        .HasColumnType("INT");

                    b.Property<bool>("is_open")
                        .HasColumnType("BIT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("vacancy_id");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("AcademyAgain.Models.VacancyApplication", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("candidate_user_id")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("DATETIME");

                    b.Property<byte>("status")
                        .HasColumnType("TINYINT");

                    b.Property<int>("vacancy_id")
                        .HasColumnType("INT");

                    b.HasKey("id");

                    b.ToTable("VacancyApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
